### ISSUE TITLE
When cloning running into permissions error.

### ISSUE THREAD

**Issue by nhrade** [scztt/vscode-supercollider#10]
I run in a permission error when cloning like this. It appears to occur when cloning the quark for the language server.

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:scztt/LanguageServer.quark.git' into submodule path '/Users/nhradek/Documents/vscode-supercollider/LanguageServer.quark' failed
Failed to clone 'LanguageServer.quark' a second time, aborting
```

**Comment by scztt** [comment]
Usually this kind of problem is because you don't have an SSH key setup for your github account, which will prevent you from cloning a repo. Try these:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection

I _think_ setup of keys is a little simpler using the official GitHub application, so you might be able to skip some steps by using that.
